BookShow/MovieCoreMvcUI/Controllers/ShowController.cs
using BookShowEntity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMvcUI.Controllers
{
    public class ShowController : Controller
    {
        private IConfiguration _configuration;

        public ShowController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async  Task<IActionResult> Index()
        {
            IEnumerable<ShowTiming> showTimingresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Show/GetShows";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTimingresult = JsonConvert.DeserializeObject<IEnumerable<ShowTiming>>(result);
                    }
                }
            }
            return View(showTimingresult);
        }
        public IActionResult ShowEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ShowEntry(ShowTiming showTiming)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(showTiming), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Show/AddShow";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Show Timing deatils Saved Successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries....!!!  :)";
                    }
                }
            }

            return View();
        }

        public async Task<IActionResult> EditShow(int showID)
        {

            ShowTiming showTiming = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Show/GetShowById?showId=" + showID;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTiming = JsonConvert.DeserializeObject<ShowTiming>(result);
                    }
                }
            }
            return View(showTiming);
        }

        [HttpPost]
        public async Task<IActionResult> EditShow(ShowTiming showTiming)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(showTiming), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Show/UpdateShow";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Show Timing deatils Saved Successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries....!!!  :)";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> DeleteShow(int ShowId)
        {
            ShowTiming showTiming = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Show/GetShowById?showId=" + ShowId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTiming = JsonConvert.DeserializeObject<ShowTiming>(result);
                    }
                }
            }

            return View(showTiming);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteShow(ShowTiming showTiming)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "Show/DeleteShow?showId=" + showTiming.Id;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Show details deleted succesfully";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Wrong Entries";
                    }
                }
            }
            return View();
        }


        /*public async Task<IActionResult> ShowShows()
        {
            IEnumerable<ShowTiming> showTimingresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Show/GetShows";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        showTimingresult = JsonConvert.DeserializeObject<IEnumerable<ShowTiming>>(result);
                    }
                }
            }
            return View(showTimingresult);
        }*/

    }
}

BookShow/MovieCoreMvcUI/Views/Show/DeleteShow.cshtml
@model BookShowEntity.ShowTiming;


<form method="post" enctype="multipart/form-data">
    <h2>Delete Show Timing Entry</h2><hr />
    <div class="group-form">
        <label>Show Id</label>
        <input type="text" asp-for="Id" class="form-control" placeholder="enter movie id" required />
    </div>
    <input type="submit" value="Delete" class="btn btn-outline-success" />

    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

BookShow/MovieCoreMvcUI/Views/Show/EditShow.cshtml
@model BookShowEntity.ShowTiming;
@{
    ViewData["Title"] = "EditShow";
}

<form method="post" enctype="multipart/form-data">
    <h2>Edit Show Timing Entry</h2><hr />
    <div class="group-form">
        <label>Show Id</label>
        <input type="text" asp-for="Id" class="form-control" placeholder="enter show id" required />
    </div>
    <div class="group-form">
        <label>Movie Id</label>
        <input type="text" asp-for="MovieId" class="form-control" placeholder="enter movie id" required />
    </div>

    <div class="group-form">
        <label>Theatre Id</label>
        <input type="text" asp-for="TheatreId" class="form-control" placeholder="enter theatre id" required />
    </div>

    <div class="group-form">
        <label>Show timing</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control" placeholder="enter show time" required />
    </div>

    <input type="submit" value="save" class="btn btn-outline-success" />
    <input type="button" value="reset" class="btn btn-outline-secondary" />
    <hr />

    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

BookShow/MovieCoreMvcUI/Views/Show/Index.cshtml
@model IEnumerable<BookShowEntity.ShowTiming>

<div>
    <hr />
    <a asp-controller="Show" asp-action="ShowEntry">Show Entry</a>
    <hr />
</div>
<div class="row">
    <div class="col-12">
        <h3>Show timings</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Show Id</th>
                    <th>Movie Id</th>
                    <th>Theatre Id</th>
                    <th>Show time</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.MovieId</td>
                        <td>@item.TheatreId</td>
                        <td>@item.ShowTime</td>

                        <td><a asp-controller="Show" asp-action="EditShow" asp-route-showId="@item.Id">Edit</a></td>
                        @*asp-route-movieID must be similar to paased movie Id in Edit Action*@
                        <td><a asp-controller="Show" asp-action="DeleteShow" asp-route-showId="@item.Id">Delete</a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

BookShow/MovieCoreMvcUI/Views/Show/ShowEntry.cshtml
@model BookShowEntity.ShowTiming;
@{
    ViewData["Title"] = "ShowEntry";
}

<div>
    <hr />
    <a asp-controller="Show" asp-action="Index">Index</a>
    <hr />
</div>

<form method="post" enctype="multipart/form-data">
    <h2>Show Entry</h2><hr />
    <div class="group-form">
        <label>movie Id</label>
        <input type="number" asp-for="MovieId" class="form-control" placeholder="enter movie Id" required />
    </div>

    <div class="group-form">
        <label>Theatre Id</label>
        <input type="number" asp-for="TheatreId" class="form-control" placeholder="enter Theatre Id" required />
    </div>

    <div class="group-form">
        <label>Show Time</label>
        <input type="datetime-local" asp-for="ShowTime" class="form-control" placeholder="enter show Time" required />
    </div>

    <input type="submit" value="save" class="btn btn-outline-success" />
    <input type="button" value="reset" class="btn btn-outline-secondary" />
    <hr />

    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>