BookShow/MovieCoreMvcUI/Controllers/BillController.cs
using BookShowEntity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace MovieCoreMvcUI.Controllers
{
    public class BillController : Controller
    {
        private IConfiguration _configuration;

        public BillController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<BookTicket> bookTicketresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/GetBookTickets";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookTicketresult = JsonConvert.DeserializeObject<IEnumerable<BookTicket>>(result);
                    }
                }
            }
            return View(bookTicketresult);
        }

        //[HttpPost]
        /*public IActionResult Index()
        {
            return View();
        }*/
    }
}

BookShow/MovieCoreMvcUI/Controllers/BookController.cs
using BookShowEntity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieCoreMvcUI.Controllers
{
    public class BookController : Controller
    {
        private IConfiguration _configuration;

        public BookController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<BookTicket> bookTicketresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/GetBookTickets";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookTicketresult = JsonConvert.DeserializeObject<IEnumerable<BookTicket>>(result);
                    }
                }
            }
            return View(bookTicketresult);
        }
        public IActionResult BookEntry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> BookEntry(BookTicket bookTicket)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(bookTicket), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/AddBooki";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Booking Ticket deatils Saved Successfully";
                        return RedirectToAction("Index", "Book");
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries....!!!  :)";
                    }
                }
            }

            return View();
        }

        public async Task<IActionResult> EditBook(int bookiID)
        {

            BookTicket bookTicket = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/GetBookById?bookiId=" + bookiID;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookTicket = JsonConvert.DeserializeObject<BookTicket>(result);
                    }
                }
            }

            return View(bookTicket);
        }

        [HttpPost]
        public async Task<IActionResult> EditBook(BookTicket bookTicket)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(bookTicket), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/UpdateBookTicket";
                using (var response = await client.PutAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Book ticket deatails Saved Successfully";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong Entries....!!!  :)";
                    }
                }
            }
            return View();
        }

        public async Task<IActionResult> DeleteBook(int BookiId)
        {
            BookTicket bookTicket = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/GetBookById?bookiId=" + BookiId;
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookTicket = JsonConvert.DeserializeObject<BookTicket>(result);
                    }
                }
            }

            return View(bookTicket);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBook(BookTicket bookTicket)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {

                string endpoint = _configuration["WebApiBaseUrl"] + "BookTicket/DeleteBookTicket?bookiId=" + bookTicket.Id;
                using (var response = await client.DeleteAsync(endpoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "Book Ticket details No Longer available of this credentials";
                    }
                    else
                    {
                        ViewBag.staus = "Error";
                        ViewBag.message = "Soory...   Wrong Entries     :)";
                    }
                }
            }
            return View();
        }

        /*public async Task<IActionResult> ShowBooks()
        {
            IEnumerable<BookTicket> bookTicketresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "BookTicket/GetBookTickets";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        bookTicketresult = JsonConvert.DeserializeObject<IEnumerable<BookTicket>>(result);
                    }
                }
            }
            return View(bookTicketresult);
        }*/

    }
}

BookShow/MovieCoreMvcUI/Views/Book/BookEntry.cshtml
@model BookShowEntity.BookTicket;
@{
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div>
    <hr />
    <a asp-controller="Book" asp-action="Index">Index</a>
    <hr />
</div>

<form method="post" enctype="multipart/form-data">
    <h2>Book Ticket Entry</h2><hr />
    <div class="group-form">
        <label>Quantity</label>
        <input type="text" asp-for="Quantity" class="form-control" placeholder="enter number of tickets" required />
    </div>

    <div class="group-form">
        <label>User Id</label>
        <input type="text" asp-for="UserId" class="form-control" placeholder="enter user Id" required />
    </div>

    <div class="group-form">
        <label>Show Id</label>
        <input type="text" asp-for="ShowId" class="form-control" placeholder="enter show Id" required />
    </div>

    <input type="submit" value="save" class="btn btn-outline-success" />
    <input type="button" value="reset" class="btn btn-outline-secondary" />
    <hr />

    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

BookShow/MovieCoreMvcUI/Views/Book/DeleteBook.cshtml
@model BookShowEntity.BookTicket;


<form method="post" enctype="multipart/form-data">
    <h2>Delete Book Ticket Entry</h2><hr />
    <div class="group-form">
        <label>Booki Id</label>
        <input type="text" asp-for="Id" class="form-control" placeholder="enter book tricket id" required />
    </div>
    <input type="submit" value="Delete" class="btn btn-outline-success" />

    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

BookShow/MovieCoreMvcUI/Views/Book/EditBook.cshtml
@model BookShowEntity.BookTicket;
@{
    ViewData["Title"] = "EditBook";
}

<form method="post" enctype="multipart/form-data">
    <h2>Edit Book Ticket Entry</h2><hr />
    <div class="group-form">
        <label>Book Ticket Id</label>
        <input type="text" asp-for="Id" class="form-control" placeholder="enter book ticket id" required />
    </div>
    <div class="group-form">
        <label>Quantity</label>
        <input type="text" asp-for="Quantity" class="form-control" placeholder="enter quantity" required />
    </div>

    <div class="group-form">
        <label>User Id</label>
        <input type="text" asp-for="UserId" class="form-control" placeholder="enter user id" required />
    </div>

    <div class="group-form">
        <label>Show Id</label>
        <input type="text" asp-for="ShowId" class="form-control" placeholder="enter show id" required />
    </div>

    <input type="submit" value="save" class="btn btn-outline-success" />
    <input type="button" value="reset" class="btn btn-outline-secondary" />
    <hr />

    @if (ViewBag.status == "Ok")
    {
        <div class="alert alert-success">
            @ViewBag.message
        </div>
    }
    else if (ViewBag.status == "Error")
    {
        <div class="alert alert-danger">
            @ViewBag.message
        </div>
    }
</form>

BookShow/MovieCoreMvcUI/Views/Book/Index.cshtml
@model IEnumerable<BookShowEntity.BookTicket>;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <hr />
    <a asp-controller="Book" asp-action="BookEntry">Book Ticket Entry</a>
    <hr />
</div>
<div class="row">
    <div class="col-12">
        <h3>Book Tickets</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>book ticket Id</th>
                    <th>Quantity</th>
                    <th>User Id</th>
                    <th>Show Id</th>
                    <th>Edit</th>
                    <th>Delete</th>
                    <th>View Bill</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Quantity</td>
                        <td>@item.UserId</td>
                        <td>@item.ShowId</td>

                        <td><a asp-controller="Book" asp-action="EditBook" asp-route-bookiId="@item.Id">Edit</a></td>
                        @*asp-route-movieID must be similar to paased movie Id in Edit Action*@
                        <td><a asp-controller="Book" asp-action="DeleteBook" asp-route-bookiId="@item.Id">Delete</a></td>

                        <td><a asp-controller="Bill" asp-action="Index" asp-route-bookiId="@item.Id">Pay Now</a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>